version: '3.8'
name: rubicon

services:
  rubicon:
    image: ${DOCKER_REGISTRY-}rubicon
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Rubicon/Dockerfile
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    # skip volume