version: '3.8'
name: rubicon

services:
  rubicon:
    image: ${DOCKER_REGISTRY-}rubicon
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Rubicon/Dockerfile
  postgres:
    image: postgis/postgis:13-3.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rubicondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    # skip volume